# -*- coding: utf-8 -*-
"""CORDENADAS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRBMsC0163TDZAgtSMDT7LLyoFBEfIeP
"""

import pandas as pd
import os

# === CONFIGURACIÓN ===
input_file = "/content/drive/MyDrive/TRABAJO DE GRADO INTERFERENCIA /MEDICIONES /FM/csv/p8_moff.csv"
output_dir = "/content/drive/MyDrive/TRABAJO DE GRADO INTERFERENCIA /MEDICIONES /FM/new_csv"
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "P8_coordenadas.csv")

# Coordenadas en decimal
latitud = 7.141888
longitud =  -73.119448
altitud = 1020.5
# === LECTURA DEL CSV ORIGINAL ===
df = pd.read_csv(input_file, sep=None, engine="python", on_bad_lines="skip")

# === ELIMINAR FILAS DE LA 2 A LA 44 ===
df = df.drop(df.index[1:54]).reset_index(drop=True)

# === ELIMINAR FILAS DE LA 2 A LA 44 ===
df = df.drop(df.index[0:3]).reset_index(drop=True)

# === RENOMBRAR LAS COLUMNAS A Y B ===
# (Asumiendo que son las dos primeras columnas)
df.rename(columns={df.columns[0]: "Frecuencia", df.columns[1]: "Magnitud"}, inplace=True)

# === AÑADIR COLUMNAS DE COORDENADAS ===
df["Latitude"] = None
df["Longitude"] = None
df["Altitude_m"] = None
df["Location"] = None

# === REORDENAR PARA QUE LAS NUEVAS VAYAN DESDE LA COLUMNA D ===
# Dejamos A–B (Frecuencia y Magnitud), luego C (si existe), luego las coordenadas
columnas_originales = [c for c in df.columns if c not in ["Latitude", "Longitude", "Altitude_m", "Location"]]
coordenadas = ["Latitude", "Longitude", "Altitude_m", "Location"]

if len(columnas_originales) >= 3:
    nuevo_orden = columnas_originales[:3] + coordenadas + columnas_originales[3:]
else:
    nuevo_orden = columnas_originales + coordenadas

df = df[nuevo_orden]

# === RELLENAR LAS NUEVAS COLUMNAS CON LOS VALORES ===
df.loc[:, "Latitude"] = latitud
df.loc[:, "Longitude"] = longitud
df.loc[:, "Altitude_m"] = altitud

# === GUARDAR NUEVO ARCHIVO ===
df.to_csv(output_file, index=False)

print("✅ Archivo generado correctamente:")
print(f"   {output_file}")
print("\n➡️ Filas 2–44 eliminadas, columnas A y B renombradas, y coordenadas añadidas desde la columna D.")

from google.colab import drive
drive.mount('/content/drive')

"""**AQUI EL CODIGO QUE SIRVE SIN INTERPOLAR**"""

import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap
from matplotlib import colors
import branca.colormap as bcm
import glob

# --- Ruta de la carpeta con tus archivos CSV ---
carpeta = '/content/drive/MyDrive/TRABAJO DE GRADO INTERFERENCIA /MEDICIONES /FM/new_csv'

# --- Buscar todos los archivos CSV en esa carpeta ---
archivos = glob.glob(carpeta + '/*.csv')

if not archivos:
    print("⚠️ No se encontraron archivos CSV en la carpeta especificada.")
else:
    print(f"✅ {len(archivos)} archivos encontrados.")

# --- Leer y unir todos los archivos ---
data_all = []
for archivo in archivos:
    try:
        df = pd.read_csv(archivo)
        df.columns = df.columns.str.strip()
        df = df.rename(columns={'Latitude': 'lat', 'Longitude': 'lon', 'Magnitud': 'mag'})
        df['lat'] = df['lat'].astype(str).str.replace(',', '.').astype(float)
        df['lon'] = df['lon'].astype(str).str.replace(',', '.').astype(float)
        df['mag'] = df['mag'].astype(str).str.replace(',', '.').astype(float)
        data_all.append(df[['lat', 'lon', 'mag']])
    except Exception as e:
        print(f"⚠️ Error al leer {archivo}: {e}")

# --- Concatenar todos los datos ---
data = pd.concat(data_all, ignore_index=True)

# --- Crear lista de puntos ---
heat_data = [[row['lat'], row['lon'], row['mag']] for _, row in data.iterrows()]

# --- Crear mapa centrado en el campus UIS ---
m = folium.Map(location=[7.1418, -73.12], zoom_start=17, tiles='OpenStreetMap')

# --- Añadir capa satelital opcional ---
folium.TileLayer('Esri.WorldImagery', name='Vista satélite').add_to(m)

# --- Mapa de calor ---
HeatMap(heat_data, radius=25, blur=20, max_zoom=18).add_to(m)

# --- Escala de colores ---
vmin, vmax = np.nanmin(data['mag']), np.nanmax(data['mag'])
colormap = bcm.LinearColormap(
    colors=['blue', 'green', 'yellow', 'red'],
    vmin=vmin, vmax=vmax,
    caption='Magnitud de señal (dBµV/m)'
)
colormap.add_to(m)

# --- Añadir control de capas ---
folium.LayerControl().add_to(m)

# --- Mostrar mapa ---
m

""" **CODIGO QUE USARÉ PARA EL TRABAJO DE GRADO**"""

import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap
import branca.colormap as bcm
import glob
import math
import os
import re
from IPython.display import display

# ==========================================================
# 1. RUTA DE LA CARPETA CON TUS CSV
# ==========================================================

carpeta = '/content/drive/MyDrive/TRABAJO DE GRADO INTERFERENCIA /MEDICIONES /FM/new_csv_EDIT'
archivos = glob.glob(carpeta + '/*.csv')

if not archivos:
    raise ValueError("⚠️ No se encontraron archivos CSV en la carpeta especificada.")
else:
    print(f"✅ {len(archivos)} archivos encontrados.")

# ==========================================================
# 2. CONFIGURACIÓN REAL DEL TRANSMISOR TX
# ==========================================================

tx_lat = 7.139785
tx_lon = -73.117335

tx_h_m = 1050.0

tx_Pt_dBm = 25.0
tx_Ltx_dB = 1.0

tx_Gmax_dBi = 10.0
tx_azimuth_deg = 340.0
tx_downtilt_deg = 0.0
tx_hpbw_az_deg = 130.0
tx_hpbw_el_deg = 70.0
tx_SLAmax_dB = 25.0
tx_FBR_dB = 30.0
tx_minGain_dBi = -20.0

# ==========================================================
# 3. CONFIGURACIÓN DEL PROCESAMIENTO Y VISUALIZACIÓN
# ==========================================================

tipo_agregacion = 'max'

# Ajustes principales del mapa de calor.
# Si el mapa se ve muy extendido, baja radio_influencia_m.
# Si se ve muy cortado, súbelo un poco.
resolucion_malla = 90
radio_influencia_m = 85
potencia_idw = 2.2
padding_m = 45

radio_heatmap = 23
blur_heatmap = 30

radios_referencia_m = [25, 50, 75, 100, 150, 200]
radio_lobulo_m = None

# ==========================================================
# 4. FUNCIONES AUXILIARES
# ==========================================================

def convertir_a_float(serie):
    return (
        serie.astype(str)
        .str.replace(',', '.', regex=False)
        .str.strip()
        .astype(float)
    )


def haversine_m(lat1, lon1, lat2, lon2):
    R = 6371000

    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    )

    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    return R * c


def bearing_deg(lat1, lon1, lat2, lon2):
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dlambda = math.radians(lon2 - lon1)

    x = math.sin(dlambda) * math.cos(phi2)
    y = (
        math.cos(phi1) * math.sin(phi2)
        - math.sin(phi1) * math.cos(phi2) * math.cos(dlambda)
    )

    bearing = math.degrees(math.atan2(x, y))
    return (bearing + 360) % 360


def diferencia_angular_deg(angulo, referencia):
    return ((angulo - referencia + 180) % 360) - 180


def punto_destino(lat, lon, bearing, distancia_m):
    R = 6371000

    bearing_rad = math.radians(bearing)
    lat1 = math.radians(lat)
    lon1 = math.radians(lon)

    lat2 = math.asin(
        math.sin(lat1) * math.cos(distancia_m / R)
        + math.cos(lat1) * math.sin(distancia_m / R) * math.cos(bearing_rad)
    )

    lon2 = lon1 + math.atan2(
        math.sin(bearing_rad) * math.sin(distancia_m / R) * math.cos(lat1),
        math.cos(distancia_m / R) - math.sin(lat1) * math.sin(lat2)
    )

    return math.degrees(lat2), math.degrees(lon2)


def extraer_punto_desde_nombre_archivo(ruta_archivo):
    nombre = os.path.basename(ruta_archivo)
    match = re.search(r'(P\d+)', nombre, re.IGNORECASE)

    if match:
        return match.group(1).upper()

    return os.path.splitext(nombre)[0]


def calcular_ganancia_tx_aproximada(
    bearing_rx_deg,
    elev_angle_deg,
    tx_azimuth_deg,
    tx_downtilt_deg,
    tx_Gmax_dBi,
    tx_hpbw_az_deg,
    tx_hpbw_el_deg,
    tx_SLAmax_dB,
    tx_FBR_dB,
    tx_minGain_dBi
):
    az_offset = diferencia_angular_deg(bearing_rx_deg, tx_azimuth_deg)
    az_offset_abs = abs(az_offset)

    el_offset = elev_angle_deg - (-tx_downtilt_deg)
    el_offset_abs = abs(el_offset)

    A_az = min(12 * (az_offset_abs / tx_hpbw_az_deg) ** 2, tx_FBR_dB)
    A_el = min(12 * (el_offset_abs / tx_hpbw_el_deg) ** 2, tx_SLAmax_dB)

    atenuacion_total = min(A_az + A_el, tx_Gmax_dBi - tx_minGain_dBi)

    Gt_eff_dBi = tx_Gmax_dBi - atenuacion_total
    Gt_eff_dBi = max(Gt_eff_dBi, tx_minGain_dBi)

    return Gt_eff_dBi, az_offset, el_offset, A_az, A_el


def agregar_por_punto(data, tipo_agregacion):
    columnas_grupo = ['punto', 'lat', 'lon', 'altitude_rx_m']

    if tipo_agregacion == 'max':
        idx = data.groupby(columnas_grupo)['mag'].idxmax()
        data_puntos = data.loc[idx].copy()
        data_puntos = data_puntos.reset_index(drop=True)

    elif tipo_agregacion == 'mean':
        data_puntos = data.groupby(columnas_grupo, as_index=False).agg({
            'mag': 'mean',
            'frecuencia_hz': 'mean'
        })

    elif tipo_agregacion == 'median':
        data_puntos = data.groupby(columnas_grupo, as_index=False).agg({
            'mag': 'median',
            'frecuencia_hz': 'median'
        })

    else:
        raise ValueError("tipo_agregacion debe ser: 'max', 'mean' o 'median'.")

    return data_puntos


def latlon_a_xy_m(lat, lon, lat0, lon0):
    lat = np.asarray(lat, dtype=float)
    lon = np.asarray(lon, dtype=float)

    x = (lon - lon0) * 111320 * np.cos(np.radians(lat0))
    y = (lat - lat0) * 110540

    return x, y


def xy_m_a_latlon(x, y, lat0, lon0):
    lat = lat0 + y / 110540
    lon = lon0 + x / (111320 * np.cos(np.radians(lat0)))

    return lat, lon


def normalizar(valor, vmin, vmax):
    if vmax == vmin:
        return 0.5

    return (valor - vmin) / (vmax - vmin)


def interpolacion_idw(data_puntos, lat0, lon0, resolucion_malla, padding_m, radio_influencia_m, potencia_idw):
    rx_x, rx_y = latlon_a_xy_m(
        data_puntos['lat'].values,
        data_puntos['lon'].values,
        lat0,
        lon0
    )

    valores = data_puntos['mag'].values.astype(float)

    tx_x, tx_y = latlon_a_xy_m(tx_lat, tx_lon, lat0, lon0)

    todos_x = np.append(rx_x, tx_x)
    todos_y = np.append(rx_y, tx_y)

    min_x = np.min(todos_x) - padding_m
    max_x = np.max(todos_x) + padding_m
    min_y = np.min(todos_y) - padding_m
    max_y = np.max(todos_y) + padding_m

    xs = np.linspace(min_x, max_x, resolucion_malla)
    ys = np.linspace(min_y, max_y, resolucion_malla)

    vmin = np.nanmin(valores)
    vmax = np.nanmax(valores)

    heat_data = []
    grid_rows = []

    for x in xs:
        for y in ys:
            distancias = np.sqrt((rx_x - x) ** 2 + (rx_y - y) ** 2)
            d_min = np.min(distancias)

            if d_min > radio_influencia_m:
                continue

            if d_min < 0.50:
                valor_interp = valores[np.argmin(distancias)]
            else:
                pesos = 1 / (distancias ** potencia_idw)
                valor_interp = np.sum(pesos * valores) / np.sum(pesos)

            lat_i, lon_i = xy_m_a_latlon(x, y, lat0, lon0)
            intensidad = normalizar(valor_interp, vmin, vmax)

            heat_data.append([float(lat_i), float(lon_i), float(intensidad)])

            grid_rows.append({
                'lat': float(lat_i),
                'lon': float(lon_i),
                'mag_interpolada': float(valor_interp),
                'intensidad_normalizada': float(intensidad),
                'distancia_punto_mas_cercano_m': float(d_min)
            })

    grid_df = pd.DataFrame(grid_rows)

    return heat_data, grid_df


# ==========================================================
# 5. LEER Y UNIR TODOS LOS CSV
# ==========================================================

data_all = []

for archivo in archivos:
    try:
        df = pd.read_csv(archivo)
        df.columns = df.columns.str.strip()

        df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

        df = df.rename(columns={
            'Frecuencia': 'frecuencia_hz',
            'Magnitud': 'mag',
            'Latitude': 'lat',
            'Longitude': 'lon',
            'Altitude_m': 'altitude_rx_m',
            'Location': 'location'
        })

        columnas_necesarias = [
            'frecuencia_hz',
            'mag',
            'lat',
            'lon',
            'altitude_rx_m'
        ]

        for col in columnas_necesarias:
            if col not in df.columns:
                raise ValueError(f"No se encontró la columna necesaria: {col}")

        df['frecuencia_hz'] = convertir_a_float(df['frecuencia_hz'])
        df['mag'] = convertir_a_float(df['mag'])
        df['lat'] = convertir_a_float(df['lat'])
        df['lon'] = convertir_a_float(df['lon'])
        df['altitude_rx_m'] = convertir_a_float(df['altitude_rx_m'])

        df = df.dropna(subset=[
            'frecuencia_hz',
            'mag',
            'lat',
            'lon',
            'altitude_rx_m'
        ])

        df['punto'] = extraer_punto_desde_nombre_archivo(archivo)

        data_all.append(
            df[['punto', 'frecuencia_hz', 'lat', 'lon', 'mag', 'altitude_rx_m']]
        )

        print(f"✅ Leído correctamente: {os.path.basename(archivo)}")

    except Exception as e:
        print(f"⚠️ Error al leer {archivo}: {e}")

if not data_all:
    raise ValueError("No se pudieron leer datos válidos desde los archivos CSV.")

data = pd.concat(data_all, ignore_index=True)

print("\n✅ Datos crudos cargados:")
display(data.head())

# ==========================================================
# 6. AGRUPAR DATOS POR PUNTO DE MEDICIÓN
# ==========================================================

data_puntos = agregar_por_punto(data, tipo_agregacion)

promedio_magnitud_por_punto = (
    data.groupby('punto', as_index=False)['mag']
    .mean()
    .rename(columns={'mag': 'mag_promedio_dbuv_m'})
)

data_puntos = data_puntos.merge(
    promedio_magnitud_por_punto,
    on='punto',
    how='left'
)

print(f"\n✅ Datos agrupados por punto usando agregación: {tipo_agregacion}")
display(data_puntos)

# ==========================================================
# 7. CÁLCULOS GEOMÉTRICOS TX-RX
# ==========================================================

data_puntos['dist_2d_m'] = data_puntos.apply(
    lambda row: haversine_m(tx_lat, tx_lon, row['lat'], row['lon']),
    axis=1
)

data_puntos['z_tx_m'] = tx_h_m
data_puntos['z_rx_m'] = data_puntos['altitude_rx_m']

data_puntos['dist_3d_m'] = np.sqrt(
    data_puntos['dist_2d_m'] ** 2
    + (data_puntos['z_tx_m'] - data_puntos['z_rx_m']) ** 2
)

data_puntos['bearing_tx_rx_deg'] = data_puntos.apply(
    lambda row: bearing_deg(tx_lat, tx_lon, row['lat'], row['lon']),
    axis=1
)

data_puntos['elev_angle_deg'] = data_puntos.apply(
    lambda row: math.degrees(
        math.atan2(
            row['z_rx_m'] - row['z_tx_m'],
            row['dist_2d_m']
        )
    ),
    axis=1
)

ganancias = data_puntos.apply(
    lambda row: calcular_ganancia_tx_aproximada(
        bearing_rx_deg=row['bearing_tx_rx_deg'],
        elev_angle_deg=row['elev_angle_deg'],
        tx_azimuth_deg=tx_azimuth_deg,
        tx_downtilt_deg=tx_downtilt_deg,
        tx_Gmax_dBi=tx_Gmax_dBi,
        tx_hpbw_az_deg=tx_hpbw_az_deg,
        tx_hpbw_el_deg=tx_hpbw_el_deg,
        tx_SLAmax_dB=tx_SLAmax_dB,
        tx_FBR_dB=tx_FBR_dB,
        tx_minGain_dBi=tx_minGain_dBi
    ),
    axis=1
)

data_puntos[
    [
        'Gt_eff_dBi',
        'az_offset_deg',
        'el_offset_deg',
        'A_az_dB',
        'A_el_dB'
    ]
] = pd.DataFrame(ganancias.tolist(), index=data_puntos.index)

print("\n✅ Cálculos TX-RX realizados:")
display(
    data_puntos[
        [
            'punto',
            'lat',
            'lon',
            'mag',
            'frecuencia_hz',
            'z_rx_m',
            'z_tx_m',
            'dist_2d_m',
            'dist_3d_m',
            'bearing_tx_rx_deg',
            'az_offset_deg',
            'elev_angle_deg',
            'Gt_eff_dBi'
        ]
    ]
)

print("\n==================== RESUMEN DE MEDICIONES ====================")
print(f"TX: lat={tx_lat:.7f}, lon={tx_lon:.7f}, azimuth={tx_azimuth_deg:.1f}°")
print(f"Ganancia máxima TX: {tx_Gmax_dBi:.1f} dBi")
print(f"HPBW azimutal: {tx_hpbw_az_deg:.1f}°")
print(f"HPBW elevación: {tx_hpbw_el_deg:.1f}°")
print(f"Puntos de medición procesados: {len(data_puntos)}")
print(f"Magnitud mínima: {data_puntos['mag'].min():.2f} dBµV/m")
print(f"Magnitud máxima: {data_puntos['mag'].max():.2f} dBµV/m")
print("===============================================================")

print("\nTabla resumen:")
print(
    data_puntos[
        [
            'punto',
            'mag',
            'frecuencia_hz',
            'dist_2d_m',
            'dist_3d_m',
            'bearing_tx_rx_deg',
            'az_offset_deg',
            'Gt_eff_dBi'
        ]
    ].to_string(index=False)
)

# ==========================================================
# 8. INTERPOLACIÓN PARA MAPA DE CALOR CONTINUO
# ==========================================================

center_lat = np.mean([tx_lat] + data_puntos['lat'].tolist())
center_lon = np.mean([tx_lon] + data_puntos['lon'].tolist())

heat_data_interpolado, grid_interpolado = interpolacion_idw(
    data_puntos=data_puntos,
    lat0=center_lat,
    lon0=center_lon,
    resolucion_malla=resolucion_malla,
    padding_m=padding_m,
    radio_influencia_m=radio_influencia_m,
    potencia_idw=potencia_idw
)

vmin = np.nanmin(data_puntos['mag'])
vmax = np.nanmax(data_puntos['mag'])

heat_data_mediciones_reales = [
    [
        row['lat'],
        row['lon'],
        normalizar(row['mag'], vmin, vmax)
    ]
    for _, row in data_puntos.iterrows()
]

print(f"\n✅ Puntos generados para superficie interpolada: {len(heat_data_interpolado)}")

# ==========================================================
# 9. CREAR MAPA BASE
# ==========================================================

m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=17,
    tiles='CartoDB positron',
    control_scale=True
)

folium.TileLayer(
    tiles='OpenStreetMap',
    name='OpenStreetMap',
    control=True
).add_to(m)

folium.TileLayer(
    tiles='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    attr='Tiles © Esri',
    name='Vista satélite',
    overlay=False,
    control=True
).add_to(m)

# ==========================================================
# 10. TÍTULO DEL MAPA
# ==========================================================

titulo_html = f"""
<div id="titulo_mapa_arrastrable" style="
position: fixed;
top: 14px;
left: 75%;
transform: translateX(-50%);
z-index: 9999;
background: rgba(255,255,255,0.94);
padding: 10px 18px;
border-radius: 12px;
box-shadow: 0 2px 10px rgba(0,0,0,0.25);
font-family: Arial;
font-size: 15px;
text-align: center;
cursor: move;
user-select: none;
-webkit-user-select: none;
">
<b>Mapa de calor de intensidad de campo medida - FM</b><br>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {{
    const titulo = document.getElementById('titulo_mapa_arrastrable');

    if (!titulo) return;

    let arrastrando = false;
    let desplazamientoX = 0;
    let desplazamientoY = 0;

    titulo.addEventListener('mousedown', function (evento) {{
        arrastrando = true;

        const rect = titulo.getBoundingClientRect();
        desplazamientoX = evento.clientX - rect.left;
        desplazamientoY = evento.clientY - rect.top;

        titulo.style.left = rect.left + 'px';
        titulo.style.top = rect.top + 'px';
        titulo.style.transform = 'none';

        evento.preventDefault();
        evento.stopPropagation();
    }});

    document.addEventListener('mousemove', function (evento) {{
        if (!arrastrando) return;

        let nuevaX = evento.clientX - desplazamientoX;
        let nuevaY = evento.clientY - desplazamientoY;

        const maxX = window.innerWidth - titulo.offsetWidth;
        const maxY = window.innerHeight - titulo.offsetHeight;

        nuevaX = Math.max(0, Math.min(nuevaX, maxX));
        nuevaY = Math.max(0, Math.min(nuevaY, maxY));

        titulo.style.left = nuevaX + 'px';
        titulo.style.top = nuevaY + 'px';

        evento.preventDefault();
        evento.stopPropagation();
    }});

    document.addEventListener('mouseup', function () {{
        arrastrando = false;
    }});

    titulo.addEventListener('click', function (evento) {{
        evento.stopPropagation();
    }});
}});
</script>
"""

m.get_root().html.add_child(folium.Element(titulo_html))

# ==========================================================
# 11. ESCALA DE COLORES
# ==========================================================

colormap = bcm.LinearColormap(
    colors=[
        '#313695',
        '#4575b4',
        '#74add1',
        '#abd9e9',
        '#ffffbf',
        '#fdae61',
        '#f46d43',
        '#d73027',
        '#a50026'
    ],
    vmin=vmin,
    vmax=vmax,
    caption='Magnitud medida / interpolada (dBµV/m)'
)

# Barra vertical de intensidad ubicada a la derecha.
# El objeto colormap se conserva para asignar colores a los marcadores.
valores_leyenda = np.linspace(vmax, vmin, 6)

etiquetas_leyenda = ""
for i, valor in enumerate(valores_leyenda):
    posicion = (i / (len(valores_leyenda) - 1)) * 100
    etiquetas_leyenda += f"""
    <div style="
        position: absolute;
        top: {posicion:.2f}%;
        left: 34px;
        transform: translateY(-50%);
        color: white;
        font-family: Arial, sans-serif;
        font-size: 15px;
        font-weight: bold;
        white-space: nowrap;
        text-shadow:
            -1px -1px 0 #000,
             1px -1px 0 #000,
            -1px  1px 0 #000,
             1px  1px 0 #000;
    ">
        {valor:.1f}
    </div>
    """

barra_intensidad_html = f"""
<div style="
    position: fixed;
    top: 50%;
    right: 24px;
    transform: translateY(-50%);
    z-index: 9998;
    height: 290px;
    width: 125px;
    pointer-events: none;
">
    <div style="
        position: absolute;
        top: 15px;
        left: 0;
        width: 22px;
        height: 260px;
        border: 1.5px solid white;
        box-shadow: 0 0 4px rgba(0,0,0,0.85);
        background: linear-gradient(
            to top,
            #313695 0%,
            #4575b4 20%,
            #74add1 40%,
            #abd9e9 48%,
            #ffffbf 55%,
            #fdae61 70%,
            #f46d43 85%,
            #d73027 93%,
            #a50026 100%
        );
    "></div>

    <div style="
        position: absolute;
        top: 15px;
        left: 0;
        width: 22px;
        height: 260px;
    ">
        {etiquetas_leyenda}
    </div>

    <div style="
        position: absolute;
        top: 15px;
        left: 88px;
        height: 260px;
        writing-mode: vertical-rl;
        transform: rotate(180deg);
        color: white;
        font-family: Arial, sans-serif;
        font-size: 14px;
        font-weight: bold;
        text-align: center;
        text-shadow:
            -1px -1px 0 #000,
             1px -1px 0 #000,
            -1px  1px 0 #000,
             1px  1px 0 #000;
    ">
        Magnitud medida / interpolada (dBµV/m)
    </div>
</div>
"""

m.get_root().html.add_child(folium.Element(barra_intensidad_html))

gradient_heatmap = {
    0.00: '#313695',
    0.20: '#4575b4',
    0.40: '#74add1',
    0.55: '#ffffbf',
    0.70: '#fdae61',
    0.85: '#f46d43',
    1.00: '#a50026'
}

# ==========================================================
# 12. LÓBULO PRINCIPAL APROXIMADO DEL TX
# ==========================================================

if radio_lobulo_m is None:
    radio_lobulo_m = max(120, data_puntos['dist_2d_m'].max() * 1.20)

fg_lobulo = folium.FeatureGroup(
    name='Lóbulo principal aproximado del TX',
    show=True
)

bearing_ini = tx_azimuth_deg - tx_hpbw_az_deg / 2
bearing_fin = tx_azimuth_deg + tx_hpbw_az_deg / 2

puntos_lobulo = [[tx_lat, tx_lon]]

for b in np.linspace(bearing_ini, bearing_fin, 55):
    lat_b, lon_b = punto_destino(tx_lat, tx_lon, b, radio_lobulo_m)
    puntos_lobulo.append([lat_b, lon_b])

puntos_lobulo.append([tx_lat, tx_lon])

folium.Polygon(
    locations=puntos_lobulo,
    color='#ff9800',
    weight=1.5,
    fill=True,
    fill_color='#ff9800',
    fill_opacity=0.12,
    opacity=0.65,
    tooltip=f'Lóbulo principal aproximado TX: azimuth {tx_azimuth_deg:.1f}°, HPBW {tx_hpbw_az_deg:.1f}°'
).add_to(fg_lobulo)

fg_lobulo.add_to(m)

# ==========================================================
# 13. MAPA DE CALOR INTERPOLADO
# ==========================================================

fg_heatmap = folium.FeatureGroup(
    name='Mapa de calor interpolado IDW',
    show=True
)

HeatMap(
    heat_data_interpolado,
    radius=radio_heatmap,
    blur=blur_heatmap,
    min_opacity=0.35,
    max_zoom=20,
    gradient=gradient_heatmap
).add_to(fg_heatmap)

fg_heatmap.add_to(m)

# ==========================================================
# 14. MAPA DE CALOR SOLO CON PUNTOS REALES
# ==========================================================

fg_heatmap_real = folium.FeatureGroup(
    name='Heatmap crudo: solo puntos reales',
    show=False
)

HeatMap(
    heat_data_mediciones_reales,
    radius=34,
    blur=24,
    min_opacity=0.45,
    max_zoom=20,
    gradient=gradient_heatmap
).add_to(fg_heatmap_real)

fg_heatmap_real.add_to(m)

# ==========================================================
# 15. PUNTOS REALES DE MEDICIÓN RX
# ==========================================================

fg_puntos = folium.FeatureGroup(
    name='Puntos reales de medición RX',
    show=True
)

for _, row in data_puntos.iterrows():

    color_punto = colormap(row['mag'])

    popup_text = f"""
    <div style="font-family: Arial; font-size: 13px;">
    <b>Punto de medición RX: {row['punto']}</b><br><br>
    <b>Latitud:</b> {row['lat']:.7f}<br>
    <b>Longitud:</b> {row['lon']:.7f}<br>
    <b>Frecuencia asociada:</b> {row['frecuencia_hz']/1e6:.3f} MHz<br>
    <b>Magnitud medida:</b> {row['mag']:.2f} dBµV/m<br><br>
    <b>Altura absoluta RX:</b> {row['z_rx_m']:.2f} m<br>
    <b>Altura absoluta TX:</b> {row['z_tx_m']:.2f} m<br>
    <b>Distancia 2D TX-RX:</b> {row['dist_2d_m']:.2f} m<br>
    <b>Distancia 3D TX-RX:</b> {row['dist_3d_m']:.2f} m<br><br>
    <b>Bearing TX-RX:</b> {row['bearing_tx_rx_deg']:.2f}°<br>
    <b>Diferencia con azimuth TX:</b> {row['az_offset_deg']:.2f}°<br>
    <b>Ángulo de elevación TX-RX:</b> {row['elev_angle_deg']:.2f}°<br>
    <b>Ganancia TX efectiva aprox.:</b> {row['Gt_eff_dBi']:.2f} dBi
    </div>
    """

    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=8,
        color='white',
        weight=2,
        fill=True,
        fill_color=color_punto,
        fill_opacity=0.96,
        popup=folium.Popup(popup_text, max_width=420),
        tooltip=f"{row['punto']} | Promedio {row['mag_promedio_dbuv_m']:.2f} dBµV/m | d2D={row['dist_2d_m']:.1f} m"
    ).add_to(fg_puntos)

    folium.Marker(
        location=[row['lat'], row['lon']],
        icon=folium.DivIcon(
            html=f"""
            <div style="
            font-size: 11px;
            font-weight: bold;
            color: black;
            background: rgba(255,255,255,0.82);
            border: 1px solid rgba(0,0,0,0.25);
            border-radius: 6px;
            padding: 1px 4px;
            transform: translate(8px, -8px);
            ">
            {row['punto']}
            </div>
            """
        )
    ).add_to(fg_puntos)

fg_puntos.add_to(m)

# ==========================================================
# 16. TRAYECTORIAS TX-RX
# ==========================================================

fg_lineas = folium.FeatureGroup(
    name='Trayectorias TX-RX',
    show=False
)

for _, row in data_puntos.iterrows():

    color_linea = colormap(row['mag'])

    folium.PolyLine(
        locations=[
            [tx_lat, tx_lon],
            [row['lat'], row['lon']]
        ],
        color=color_linea,
        weight=2,
        opacity=0.52,
        tooltip=(
            f"{row['punto']} | "
            f"d2D={row['dist_2d_m']:.1f} m | "
            f"d3D={row['dist_3d_m']:.1f} m | "
            f"{row['mag']:.2f} dBµV/m"
        )
    ).add_to(fg_lineas)

fg_lineas.add_to(m)

# ==========================================================
# 17. MARCADOR REAL DEL TRANSMISOR TX
# ==========================================================

popup_tx = f"""
<div style="font-family: Arial; font-size: 13px;">
<b>Antena transmisora TX</b><br><br>
<b>Latitud:</b> {tx_lat:.7f}<br>
<b>Longitud:</b> {tx_lon:.7f}<br>
<b>Altura absoluta TX:</b> {tx_h_m:.2f} m<br>
<b>Potencia TX:</b> {tx_Pt_dBm:.2f} dBm<br>
<b>Pérdida TX:</b> {tx_Ltx_dB:.2f} dB<br><br>
<b>Ganancia máxima:</b> {tx_Gmax_dBi:.2f} dBi<br>
<b>Azimuth:</b> {tx_azimuth_deg:.2f}°<br>
<b>Downtilt:</b> {tx_downtilt_deg:.2f}°<br>
<b>HPBW azimutal:</b> {tx_hpbw_az_deg:.2f}°<br>
<b>HPBW elevación:</b> {tx_hpbw_el_deg:.2f}°<br>
<b>FBR:</b> {tx_FBR_dB:.2f} dB<br>
<b>SLAmax:</b> {tx_SLAmax_dB:.2f} dB<br>
<b>Ganancia mínima:</b> {tx_minGain_dBi:.2f} dBi
</div>
"""

folium.Marker(
    location=[tx_lat, tx_lon],
    popup=folium.Popup(popup_tx, max_width=420),
    tooltip='Antena transmisora TX',
    icon=folium.Icon(
        color='red',
        icon='signal',
        prefix='fa'
    )
).add_to(m)

folium.Marker(
    location=[tx_lat, tx_lon],
    icon=folium.DivIcon(
        html=f"""
        <div style="
        font-size: 12px;
        font-weight: bold;
        color: white;
        background: rgba(180,0,0,0.88);
        border-radius: 8px;
        padding: 3px 7px;
        transform: translate(10px, -12px);
        box-shadow: 0 1px 4px rgba(0,0,0,0.35);
        ">
        TX
        </div>
        """
    )
).add_to(m)

# ==========================================================
# 18. CÍRCULOS DE REFERENCIA ALREDEDOR DEL TX
# ==========================================================

fg_radios = folium.FeatureGroup(
    name='Radios de referencia TX',
    show=False
)

for radio in radios_referencia_m:
    folium.Circle(
        location=[tx_lat, tx_lon],
        radius=radio,
        color='#b30000',
        fill=False,
        weight=1,
        opacity=0.35,
        tooltip=f'Radio de referencia: {radio} m'
    ).add_to(fg_radios)

fg_radios.add_to(m)

# ==========================================================
# 19. NOTA METODOLÓGICA EN EL MAPA
# ==========================================================

nota_html = f"""
<div style="
position: fixed;
bottom: 28px;
left: 12px;
z-index: 9999;
background: rgba(255,255,255,0.92);
padding: 9px 12px;
border-radius: 10px;
box-shadow: 0 2px 8px rgba(0,0,0,0.25);
font-family: Arial;
font-size: 12px;
max-width: 315px;
">
<b>Nota:</b> el mapa de calor corresponde a una interpolación IDW de los puntos medidos.
Los marcadores circulares indican las mediciones reales usadas para generar la superficie.
</div>
"""

m.get_root().html.add_child(folium.Element(nota_html))

# ==========================================================
# 20. AJUSTAR VISTA AL ÁREA DE DATOS
# ==========================================================

min_lat = min([tx_lat] + data_puntos['lat'].tolist())
max_lat = max([tx_lat] + data_puntos['lat'].tolist())
min_lon = min([tx_lon] + data_puntos['lon'].tolist())
max_lon = max([tx_lon] + data_puntos['lon'].tolist())

m.fit_bounds([
    [min_lat, min_lon],
    [max_lat, max_lon]
], padding=(45, 45))

# ==========================================================
# 21. CONTROL DE CAPAS
# ==========================================================

folium.LayerControl(collapsed=False, position='topleft').add_to(m)

# ==========================================================
# 22. GUARDAR RESULTADOS
# ==========================================================

ruta_salida_mapa = '/content/mapa_mediciones_tdt_tx_real_mejorado.html'
m.save(ruta_salida_mapa)

ruta_salida_tabla = '/content/resultados_resumen_tdt_tx_real_mejorado.csv'
data_puntos.to_csv(ruta_salida_tabla, index=False)

ruta_salida_interpolacion = '/content/superficie_interpolada_tdt_idw.csv'
grid_interpolado.to_csv(ruta_salida_interpolacion, index=False)

print(f"\n✅ Mapa guardado en: {ruta_salida_mapa}")
print(f"✅ Tabla resumen guardada en: {ruta_salida_tabla}")
print(f"✅ Superficie interpolada guardada en: {ruta_salida_interpolacion}")

# ==========================================================
# 23. MOSTRAR MAPA EN COLAB
# ==========================================================

m

pip install imgkit

"""EXPERIMENTAR"""

